spring:
  application:
    name: spirngcloud-rabbitmq
  # mq配置
  rabbitmq:
    host: 47.111.166.190
    port: 5672
    username: ryanchou
    password: RyanChou514
    connection-timeout: 15000
    cache:
      channel:
        size: 200
    # 消息发送到rabbitmq broker cluster需要回调
    publisher-confirms: true
    # 交换机将消息投递至队列失败时需要回调
    publisher-returns: true
    listener:
      # 手动确认消息已被消费
      simple:
        acknowledge-mode: manual
        # consumer的并发数
        concurrency: 5
        max-concurrency: 10
    template:
      # 当mandatory标志位设置为true时，如果exchange根据自身类型和消息routeKey无法找到一个符合条件的queue，
      # 那么会调用basic.return方法将消息返还给生产者；当mandatory设为false时，出现上述情形broker会直接将消息扔掉。
      mandatory: true
